version: '3'
services:
  frontend:
    image: gingerfenix/ci-kata-madness:frontendimage
    ports:
      - "5000:80"
  backend:
    image: gingerfenix/ci-kata-madness:backendimage
    ports:
      - "8080:80"
